name: golang-dev

services:
  dev:
    # 建議放跟 Dockerfile 同層；改路徑請同步 context
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-dev
    user: vscode

    env_file:
      - ./devcontainer.env

    volumes:
      # 你的程式碼 / Go module cache / Claude 設定檔
      - ..:/workspace
    
    # ports:
    #   - "8080:8080"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
